### PR TITLE
HeroComponent does not implement OnInit

### PR DESCRIPTION
**Pull request by nickroberts**

### CODE REVIEW

**Comment by johnpapa** [comment]
thanks :)

works with it there because it does not generate js, but still a good catch!

**Comment by nickroberts** [comment]
Thanks! tsc wouldn't compile without removing that. Once again, great talks this week!

**Comment by hiteshsahu** [comment]
Add imports for lifecycle

import { Component, OnInit, ViewEncapsulation } from '@angular/core';

**Comment by hiteshsahu** [comment]
Code Snippet

```
export class AppComponent   implements OnInit{
title = 'The App Still Works!';

  ngOnInit() {
  // Do initializaing/service call
  this.title = 'Updated from onInit!';
  }
  //Angular creates, updates, and destroys components as the user moves through the application.
  //Your app can take action at each moment in this lifecycle through optional lifecycle hooks,
  //like ngOnInit() declared above.
}
```

**Pull request merged**
